# Generated by Django 5.1.6 on 2025-03-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=200)),
                ('MobileNumber', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'reg_table',
            },
        ),
    ]
