# Generated by Django 5.1.6 on 2025-03-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='email',
            new_name='Email',
        ),
    ]
