# Generated by Django 5.1.6 on 2025-03-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiys', '0002_rename_email_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='MobileNumber',
            field=models.CharField(default=123, max_length=10),
        ),
    ]
