# Generated by Django 5.1.6 on 2025-03-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiys', '0003_alter_registration_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='MobileNumber',
            field=models.CharField(max_length=10),
        ),
    ]
